"""Le calendrier des fêtes : à quel saint, ou à quelle fête, appartient une date.

Une donnée fixe, pas un appel. Le calendrier civil français ne bouge pas d'une année sur
l'autre, et une table locale a trois avantages sur un modèle à qui on la demanderait :
elle ne coûte rien, elle ne peut pas inventer, et elle rend la même chose au renvoi
qu'à l'envoi.

Chaque entrée est écrite comme elle apparaît dans la lettre, en apposition derrière la
date : « Vendredi 28 août 2026, saint Augustin. » Les fêtes civiles et religieuses
prennent leur article — « la Toussaint », « le Jour de l'An » — et se lisent au même
endroit sans que la phrase ait à changer de forme.

C'est le calendrier des postes, celui des agendas français. Les éditions varient sur
quelques jours — un saint local, un second prénom retenu plutôt qu'un autre. Corriger
une date se fait ici, et nulle part ailleurs.

Les fêtes mobiles — Pâques, l'Ascension, la Pentecôte — n'y sont pas : elles tombent à
une date différente chaque année et ne se rangent pas dans une table indexée par le
jour et le mois. Le saint fixe du jour est alors celui qui s'affiche.
"""

from __future__ import annotations

import datetime as dt

#: La fête de chaque date, indexée par (mois, jour), prête à être lue en apposition.
FETES: dict[tuple[int, int], str] = {
    # -- janvier ------------------------------------------------------------
    (1, 1): "le Jour de l'An",
    (1, 2): "saint Basile",
    (1, 3): "sainte Geneviève",
    (1, 4): "saint Odilon",
    (1, 5): "saint Édouard",
    (1, 6): "l'Épiphanie",
    (1, 7): "saint Raymond",
    (1, 8): "saint Lucien",
    (1, 9): "sainte Alix",
    (1, 10): "saint Guillaume",
    (1, 11): "saint Paulin",
    (1, 12): "sainte Tatiana",
    (1, 13): "sainte Yvette",
    (1, 14): "sainte Nina",
    (1, 15): "saint Rémi",
    (1, 16): "saint Marcel",
    (1, 17): "sainte Roseline",
    (1, 18): "sainte Prisca",
    (1, 19): "saint Marius",
    (1, 20): "saint Sébastien",
    (1, 21): "sainte Agnès",
    (1, 22): "saint Vincent",
    (1, 23): "saint Barnard",
    (1, 24): "saint François de Sales",
    (1, 25): "la conversion de saint Paul",
    (1, 26): "sainte Paule",
    (1, 27): "sainte Angèle",
    (1, 28): "saint Thomas d'Aquin",
    (1, 29): "saint Gildas",
    (1, 30): "sainte Martine",
    (1, 31): "sainte Marcelle",
    # -- février ------------------------------------------------------------
    (2, 1): "sainte Ella",
    (2, 2): "la Chandeleur",
    (2, 3): "saint Blaise",
    (2, 4): "sainte Véronique",
    (2, 5): "sainte Agathe",
    (2, 6): "saint Gaston",
    (2, 7): "sainte Eugénie",
    (2, 8): "sainte Jacqueline",
    (2, 9): "sainte Apolline",
    (2, 10): "saint Arnaud",
    (2, 11): "Notre-Dame de Lourdes",
    (2, 12): "saint Félix",
    (2, 13): "sainte Béatrice",
    (2, 14): "saint Valentin",
    (2, 15): "saint Claude",
    (2, 16): "sainte Julienne",
    (2, 17): "saint Alexis",
    (2, 18): "sainte Bernadette",
    (2, 19): "saint Gabin",
    (2, 20): "sainte Aimée",
    (2, 21): "saint Pierre-Damien",
    (2, 22): "sainte Isabelle",
    (2, 23): "saint Lazare",
    (2, 24): "saint Modeste",
    (2, 25): "saint Roméo",
    (2, 26): "saint Nestor",
    (2, 27): "sainte Honorine",
    (2, 28): "saint Romain",
    (2, 29): "saint Auguste",
    # -- mars ---------------------------------------------------------------
    (3, 1): "saint Aubin",
    (3, 2): "saint Charles le Bon",
    (3, 3): "saint Guénolé",
    (3, 4): "saint Casimir",
    (3, 5): "sainte Olive",
    (3, 6): "sainte Colette",
    (3, 7): "sainte Félicité",
    (3, 8): "saint Jean de Dieu",
    (3, 9): "sainte Françoise",
    (3, 10): "saint Vivien",
    (3, 11): "sainte Rosine",
    (3, 12): "sainte Justine",
    (3, 13): "saint Rodrigue",
    (3, 14): "sainte Mathilde",
    (3, 15): "sainte Louise",
    (3, 16): "sainte Bénédicte",
    (3, 17): "saint Patrice",
    (3, 18): "saint Cyrille",
    (3, 19): "saint Joseph",
    (3, 20): "saint Herbert",
    (3, 21): "sainte Clémence",
    (3, 22): "sainte Léa",
    (3, 23): "saint Victorien",
    (3, 24): "sainte Catherine de Suède",
    (3, 25): "l'Annonciation",
    (3, 26): "sainte Larissa",
    (3, 27): "saint Habib",
    (3, 28): "saint Gontran",
    (3, 29): "sainte Gwladys",
    (3, 30): "saint Amédée",
    (3, 31): "saint Benjamin",
    # -- avril --------------------------------------------------------------
    (4, 1): "saint Hugues",
    (4, 2): "sainte Sandrine",
    (4, 3): "saint Richard",
    (4, 4): "saint Isidore",
    (4, 5): "sainte Irène",
    (4, 6): "saint Marcellin",
    (4, 7): "saint Jean-Baptiste de la Salle",
    (4, 8): "sainte Julie",
    (4, 9): "saint Gautier",
    (4, 10): "saint Fulbert",
    (4, 11): "saint Stanislas",
    (4, 12): "saint Jules",
    (4, 13): "sainte Ida",
    (4, 14): "saint Maxime",
    (4, 15): "saint Paterne",
    (4, 16): "saint Benoît-Joseph",
    (4, 17): "saint Anicet",
    (4, 18): "saint Parfait",
    (4, 19): "sainte Emma",
    (4, 20): "sainte Odette",
    (4, 21): "saint Anselme",
    (4, 22): "saint Alexandre",
    (4, 23): "saint Georges",
    (4, 24): "saint Fidèle",
    (4, 25): "saint Marc",
    (4, 26): "sainte Alida",
    (4, 27): "sainte Zita",
    (4, 28): "sainte Valérie",
    (4, 29): "sainte Catherine de Sienne",
    (4, 30): "saint Robert",
    # -- mai ----------------------------------------------------------------
    (5, 1): "la Fête du Travail",
    (5, 2): "saint Boris",
    (5, 3): "saint Philippe et saint Jacques",
    (5, 4): "saint Sylvain",
    (5, 5): "sainte Judith",
    (5, 6): "sainte Prudence",
    (5, 7): "sainte Gisèle",
    (5, 8): "la Victoire de 1945",
    (5, 9): "saint Pacôme",
    (5, 10): "sainte Solange",
    (5, 11): "sainte Estelle",
    (5, 12): "saint Achille",
    (5, 13): "sainte Rolande",
    (5, 14): "saint Matthias",
    (5, 15): "sainte Denise",
    (5, 16): "saint Honoré",
    (5, 17): "saint Pascal",
    (5, 18): "saint Éric",
    (5, 19): "saint Yves",
    (5, 20): "saint Bernardin",
    (5, 21): "saint Constantin",
    (5, 22): "saint Émile",
    (5, 23): "saint Didier",
    (5, 24): "saint Donatien",
    (5, 25): "sainte Sophie",
    (5, 26): "saint Bérenger",
    (5, 27): "saint Augustin de Cantorbéry",
    (5, 28): "saint Germain",
    (5, 29): "saint Aymar",
    (5, 30): "saint Ferdinand",
    (5, 31): "la Visitation",
    # -- juin ---------------------------------------------------------------
    (6, 1): "saint Justin",
    (6, 2): "sainte Blandine",
    (6, 3): "saint Kévin",
    (6, 4): "sainte Clotilde",
    (6, 5): "saint Igor",
    (6, 6): "saint Norbert",
    (6, 7): "saint Gilbert",
    (6, 8): "saint Médard",
    (6, 9): "sainte Diane",
    (6, 10): "saint Landry",
    (6, 11): "saint Barnabé",
    (6, 12): "saint Guy",
    (6, 13): "saint Antoine de Padoue",
    (6, 14): "saint Élisée",
    (6, 15): "sainte Germaine",
    (6, 16): "saint Jean-François Régis",
    (6, 17): "saint Hervé",
    (6, 18): "saint Léonce",
    (6, 19): "saint Romuald",
    (6, 20): "saint Silvère",
    (6, 21): "saint Rodolphe",
    (6, 22): "saint Alban",
    (6, 23): "sainte Audrey",
    (6, 24): "saint Jean-Baptiste",
    (6, 25): "saint Prosper",
    (6, 26): "saint Anthelme",
    (6, 27): "saint Fernand",
    (6, 28): "saint Irénée",
    (6, 29): "saint Pierre et saint Paul",
    (6, 30): "saint Martial",
    # -- juillet ------------------------------------------------------------
    (7, 1): "saint Thierry",
    (7, 2): "saint Martinien",
    (7, 3): "saint Thomas",
    (7, 4): "saint Florent",
    (7, 5): "saint Antoine-Marie",
    (7, 6): "sainte Mariette",
    (7, 7): "saint Raoul",
    (7, 8): "saint Thibaut",
    (7, 9): "sainte Amandine",
    (7, 10): "saint Ulrich",
    (7, 11): "saint Benoît",
    (7, 12): "saint Olivier",
    (7, 13): "saint Henri et saint Joël",
    (7, 14): "la Fête nationale",
    (7, 15): "saint Donald",
    (7, 16): "Notre-Dame du Mont-Carmel",
    (7, 17): "sainte Charlotte",
    (7, 18): "saint Frédéric",
    (7, 19): "saint Arsène",
    (7, 20): "sainte Marina",
    (7, 21): "saint Victor",
    (7, 22): "sainte Marie-Madeleine",
    (7, 23): "sainte Brigitte",
    (7, 24): "sainte Christine",
    (7, 25): "saint Jacques",
    (7, 26): "sainte Anne et saint Joachim",
    (7, 27): "sainte Nathalie",
    (7, 28): "saint Samson",
    (7, 29): "sainte Marthe",
    (7, 30): "sainte Juliette",
    (7, 31): "saint Ignace de Loyola",
    # -- août ---------------------------------------------------------------
    (8, 1): "saint Alphonse",
    (8, 2): "saint Julien Eymard",
    (8, 3): "sainte Lydie",
    (8, 4): "saint Jean-Marie Vianney",
    (8, 5): "saint Abel",
    (8, 6): "la Transfiguration",
    (8, 7): "saint Gaétan",
    (8, 8): "saint Dominique",
    (8, 9): "saint Amour",
    (8, 10): "saint Laurent",
    (8, 11): "sainte Claire",
    (8, 12): "sainte Clarisse",
    (8, 13): "saint Hippolyte",
    (8, 14): "saint Évrard",
    (8, 15): "l'Assomption",
    (8, 16): "saint Armel",
    (8, 17): "saint Hyacinthe",
    (8, 18): "sainte Hélène",
    (8, 19): "saint Jean Eudes",
    (8, 20): "saint Bernard",
    (8, 21): "saint Christophe",
    (8, 22): "saint Fabrice",
    (8, 23): "sainte Rose de Lima",
    (8, 24): "saint Barthélemy",
    (8, 25): "saint Louis",
    (8, 26): "sainte Natacha",
    (8, 27): "sainte Monique",
    (8, 28): "saint Augustin",
    (8, 29): "sainte Sabine",
    (8, 30): "saint Fiacre",
    (8, 31): "saint Aristide",
    # -- septembre ----------------------------------------------------------
    (9, 1): "saint Gilles",
    (9, 2): "sainte Ingrid",
    (9, 3): "saint Grégoire",
    (9, 4): "sainte Rosalie",
    (9, 5): "sainte Raïssa",
    (9, 6): "saint Bertrand",
    (9, 7): "sainte Reine",
    (9, 8): "la Nativité de Marie",
    (9, 9): "saint Alain",
    (9, 10): "sainte Inès",
    (9, 11): "saint Adelphe",
    (9, 12): "saint Apollinaire",
    (9, 13): "saint Aimé",
    (9, 14): "la Croix glorieuse",
    (9, 15): "saint Roland",
    (9, 16): "sainte Édith",
    (9, 17): "saint Renaud",
    (9, 18): "sainte Nadège",
    (9, 19): "sainte Émilie",
    (9, 20): "saint Davy",
    (9, 21): "saint Matthieu",
    (9, 22): "saint Maurice",
    (9, 23): "saint Constant",
    (9, 24): "sainte Thècle",
    (9, 25): "saint Hermann",
    (9, 26): "saint Côme et saint Damien",
    (9, 27): "saint Vincent de Paul",
    (9, 28): "saint Venceslas",
    (9, 29): "saint Michel, saint Gabriel et saint Raphaël",
    (9, 30): "saint Jérôme",
    # -- octobre ------------------------------------------------------------
    (10, 1): "sainte Thérèse de l'Enfant-Jésus",
    (10, 2): "saint Léger",
    (10, 3): "saint Gérard",
    (10, 4): "saint François d'Assise",
    (10, 5): "sainte Fleur",
    (10, 6): "saint Bruno",
    (10, 7): "saint Serge",
    (10, 8): "sainte Pélagie",
    (10, 9): "saint Denis",
    (10, 10): "saint Ghislain",
    (10, 11): "saint Firmin",
    (10, 12): "saint Wilfried",
    (10, 13): "saint Géraud",
    (10, 14): "saint Juste",
    (10, 15): "sainte Thérèse d'Avila",
    (10, 16): "sainte Edwige",
    (10, 17): "saint Baudouin",
    (10, 18): "saint Luc",
    (10, 19): "saint René",
    (10, 20): "sainte Adeline",
    (10, 21): "sainte Céline",
    (10, 22): "sainte Élodie",
    (10, 23): "saint Jean de Capistran",
    (10, 24): "saint Florentin",
    (10, 25): "saint Crépin",
    (10, 26): "saint Dimitri",
    (10, 27): "sainte Émeline",
    (10, 28): "saint Simon et saint Jude",
    (10, 29): "saint Narcisse",
    (10, 30): "sainte Bienvenue",
    (10, 31): "saint Quentin",
    # -- novembre -----------------------------------------------------------
    (11, 1): "la Toussaint",
    (11, 2): "le jour des Défunts",
    (11, 3): "saint Hubert",
    (11, 4): "saint Charles",
    (11, 5): "sainte Sylvie",
    (11, 6): "sainte Bertille",
    (11, 7): "sainte Carine",
    (11, 8): "saint Geoffroy",
    (11, 9): "saint Théodore",
    (11, 10): "saint Léon",
    (11, 11): "l'Armistice de 1918",
    (11, 12): "saint Christian",
    (11, 13): "saint Brice",
    (11, 14): "saint Sidoine",
    (11, 15): "saint Albert",
    (11, 16): "sainte Marguerite",
    (11, 17): "sainte Élisabeth",
    (11, 18): "sainte Aude",
    (11, 19): "saint Tanguy",
    (11, 20): "saint Edmond",
    (11, 21): "la Présentation de Marie",
    (11, 22): "sainte Cécile",
    (11, 23): "saint Clément",
    (11, 24): "sainte Flora",
    (11, 25): "sainte Catherine",
    (11, 26): "sainte Delphine",
    (11, 27): "saint Séverin",
    (11, 28): "saint Jacques de la Marche",
    (11, 29): "saint Saturnin",
    (11, 30): "saint André",
    # -- décembre -----------------------------------------------------------
    (12, 1): "sainte Florence",
    (12, 2): "sainte Viviane",
    (12, 3): "saint François-Xavier",
    (12, 4): "sainte Barbara",
    (12, 5): "saint Gérald",
    (12, 6): "saint Nicolas",
    (12, 7): "saint Ambroise",
    (12, 8): "l'Immaculée Conception",
    (12, 9): "saint Pierre Fourier",
    (12, 10): "saint Romaric",
    (12, 11): "saint Daniel",
    (12, 12): "sainte Jeanne-Françoise de Chantal",
    (12, 13): "sainte Lucie",
    (12, 14): "sainte Odile",
    (12, 15): "sainte Ninon",
    (12, 16): "sainte Alice",
    (12, 17): "saint Gaël",
    (12, 18): "saint Gatien",
    (12, 19): "saint Urbain",
    (12, 20): "saint Abraham",
    (12, 21): "saint Pierre Canisius",
    (12, 22): "sainte Françoise-Xavière",
    (12, 23): "saint Armand",
    (12, 24): "sainte Adèle",
    (12, 25): "Noël",
    (12, 26): "saint Étienne",
    (12, 27): "saint Jean",
    (12, 28): "les Saints Innocents",
    (12, 29): "saint David",
    (12, 30): "saint Roger",
    (12, 31): "saint Sylvestre",
}


def du_jour(day: dt.date) -> str:
    """La fête de cette date, chaîne vide si la table n'en a pas.

    Chaîne vide et non `None` : elle se concatène alors sans que l'appelant ait à
    tester, et la lettre perd simplement une apposition.
    """
    return FETES.get((day.month, day.day), "")
